
target 'Chenglong' do

pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'SDWebImage' , '~> 3.8.1'
pod 'Lockbox' , '~> 2.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'BlocksKit', '~> 2.2.5'
pod 'PureLayout'
#pod 'TWRDownloadManager'

end
